changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
        - "breaking"
    - title: "Features"
      labels:
        - "feature"
        - "feat"
    - title: "Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation"
      labels:
        - "docs"
    - title: "Chore & Maintenance"
      labels:
        - "chore"
        - "maintenance"
    - title: "Other Changes"
      labels:
        - "*"
