name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write
  discussions: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          labels: "autorelease: pending"
      - name: Enable auto-merge for release PR
        if: ${{ steps.release.outputs.pr }}
        run: gh pr merge --auto --squash "${{ steps.release.outputs.pr }}"
        env:
          GH_TOKEN: ${{ github.token }}
